### ISSUE TITLE
Include Flask-RESTplus in requirement.txt file

### ISSUE THREAD

**Issue by dingding2018** [nyu-devops-fall18/products#109]
**As a developer  
**I need to add flask-RESTplus library to requirement.txt file
**So that I can use it to create swagger docs.

**Assumptions:** 
* When I run the python program to automatically generate the swagger docs, it will be no error.

**Acceptance Criteria:**
Given requirement.txt is updated,
When running the python program,
Then the swagger docs can be generated and checked in the browser.

**Comment by richa-d** [comment]
Estimates should be either 2, 5 or 8. So I am setting this to 2.
