### ISSUE TITLE
List Products by ID, Category and Name needs to have a function in the model.py file

### ISSUE THREAD

**Issue by ss11485** [nyu-devops-fall18/products#25]
Describe the Problem:

Describe what happened in as much detail as needed

List Products by ID, Category, and Name needs to have a function in the model.py file

Steps to Reproduce:

Go to the URL for /products and an error comes up

Expected Result:

Tell us what you expected to happen

Should return all products by default, or return products filtered by name or category

Observed Result:

Tell us what you actually observed

An error was observed while accessing the /products page

**Comment by dingding2018** [comment]
Bugs solved. Now the page works normally.
The problems of list by name and by category were due to the case insensitive of Sqlalchemy. 
# @ss11485

**Comment by ss11485** [comment]
@dingding2018 Please send a pull request with your changes to resolve this bug. Thank you!
