### ISSUE TITLE
Add Vagrant support so that developers can work locally

### ISSUE THREAD

**Issue by richa-d** [nyu-devops-fall18/products#3]
**As a** developer  
**I need** to be able to work locally with Vagrant
**So that** we have a common development environment  

**Assumptions:** 
* Use Vagrant and VirtualBox for creating a local development environment

**Acceptance Criteria:**
```
When I issue git clone on the project
And I change into the project folder
And I issue vagrant up
Then I should have a complete development environment on my workstation
```

**Comment by ss11485** [comment]
@richa-d Can you please take a look at the Vagrantfile and check if it works on your system? Thanks!
